### ISSUE TITLE
[request] Add path and storeAs methods

### ISSUE THREAD

**Issue by abordage** [halimtuhu/array-images#1]
Hi. Thanks for the package.
Do you plan to add the path and storeAs methods to customize file storage?

I talk about it: https://nova.laravel.com/docs/1.0/resources/file-fields.html#customization

**Comment by halimtuhu** [comment]
sure, that will be great. thanks for your feedback. I really really
appreciate it..

Pada tanggal Kam, 25 Okt 2018 pukul 01.19 abordage <notifications@github.com>
menulis:

**Comment by halimtuhu** [comment]
done on latest update
